### ISSUE TITLE
aimBot() should spinUp

### ISSUE THREAD

**Issue by cpostbitbuckets** [BitBucketsFRC4183/FRC2020_Infinite_Recharge#198]
The aimBot function currently calls autoAim. autoAim only changes elevation. It should change elevation, rotate to target, and spinUp motor to speed based on distance.

We can have the shooterCalculator calculate auto speed and elevation in periodic, then just update the targets while autoAim is held.

We might also want autoAim to enable the limelight light while held.

**Comment by Sajo8** [comment]
if autoAim() is not being pressed then it should also zero the elevation
